ALTER  TABLE MOUVEMENTCAISSE ADD numero varchar(250);

ALTER TABle mouvementcaisse ADD reference varchar(250);


INSERT INTO COMPTA_COMPTE (ID,COMPTE,LIBELLE,TYPECOMPTE,CLASSY,ANALYTIQUE_OBLI,IDJOURNAL) VALUES
	 ('ccppp','COC007913','Kaonty oh','7','6',NULL,'COMP000039');